version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci4-app
    ports:
      - "8080:80"  # Host port 8080 -> Apache port 80
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3307
      DB_DATABASE: ci4db
      DB_USERNAME: root
      DB_PASSWORD: ""
    networks:
      - ci4-network

networks:
  ci4-network:
    driver: bridge
